// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: sdk/proto/cph.proto

package cphv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClawPlugin_Handshake_FullMethodName            = "/cph.v1.ClawPlugin/Handshake"
	ClawPlugin_Login_FullMethodName                = "/cph.v1.ClawPlugin/Login"
	ClawPlugin_Refresh_FullMethodName              = "/cph.v1.ClawPlugin/Refresh"
	ClawPlugin_GetProfile_FullMethodName           = "/cph.v1.ClawPlugin/GetProfile"
	ClawPlugin_ListModels_FullMethodName           = "/cph.v1.ClawPlugin/ListModels"
	ClawPlugin_Chat_FullMethodName                 = "/cph.v1.ClawPlugin/Chat"
	ClawPlugin_ListTaskCapabilities_FullMethodName = "/cph.v1.ClawPlugin/ListTaskCapabilities"
	ClawPlugin_RunTask_FullMethodName              = "/cph.v1.ClawPlugin/RunTask"
)

// ClawPluginClient is the client API for ClawPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClawPlugin —— 核心作为 gRPC 客户端调用插件（go-plugin 子进程模型）
type ClawPluginClient interface {
	// 安装/启动握手：协议版本校验 + 获取 Manifest
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// 账号能力
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResult, error)
	Refresh(ctx context.Context, in *CredentialBlob, opts ...grpc.CallOption) (*RefreshResult, error)
	GetProfile(ctx context.Context, in *CredentialBlob, opts ...grpc.CallOption) (*AccountProfile, error)
	// 模型目录
	ListModels(ctx context.Context, in *CredentialBlob, opts ...grpc.CallOption) (*ModelList, error)
	// 核心链路：统一信封进，事件流出
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEvent], error)
	// 任务能力（核心调度触发时调用）
	ListTaskCapabilities(ctx context.Context, in *TaskCapabilitiesRequest, opts ...grpc.CallOption) (*TaskCapabilities, error)
	RunTask(ctx context.Context, in *RunTaskRequest, opts ...grpc.CallOption) (*RunTaskResponse, error)
}

type clawPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewClawPluginClient(cc grpc.ClientConnInterface) ClawPluginClient {
	return &clawPluginClient{cc}
}

func (c *clawPluginClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, ClawPlugin_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawPluginClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResult)
	err := c.cc.Invoke(ctx, ClawPlugin_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawPluginClient) Refresh(ctx context.Context, in *CredentialBlob, opts ...grpc.CallOption) (*RefreshResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshResult)
	err := c.cc.Invoke(ctx, ClawPlugin_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawPluginClient) GetProfile(ctx context.Context, in *CredentialBlob, opts ...grpc.CallOption) (*AccountProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountProfile)
	err := c.cc.Invoke(ctx, ClawPlugin_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawPluginClient) ListModels(ctx context.Context, in *CredentialBlob, opts ...grpc.CallOption) (*ModelList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelList)
	err := c.cc.Invoke(ctx, ClawPlugin_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawPluginClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClawPlugin_ServiceDesc.Streams[0], ClawPlugin_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, StreamEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClawPlugin_ChatClient = grpc.ServerStreamingClient[StreamEvent]

func (c *clawPluginClient) ListTaskCapabilities(ctx context.Context, in *TaskCapabilitiesRequest, opts ...grpc.CallOption) (*TaskCapabilities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskCapabilities)
	err := c.cc.Invoke(ctx, ClawPlugin_ListTaskCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawPluginClient) RunTask(ctx context.Context, in *RunTaskRequest, opts ...grpc.CallOption) (*RunTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunTaskResponse)
	err := c.cc.Invoke(ctx, ClawPlugin_RunTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClawPluginServer is the server API for ClawPlugin service.
// All implementations must embed UnimplementedClawPluginServer
// for forward compatibility.
//
// ClawPlugin —— 核心作为 gRPC 客户端调用插件（go-plugin 子进程模型）
type ClawPluginServer interface {
	// 安装/启动握手：协议版本校验 + 获取 Manifest
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	// 账号能力
	Login(context.Context, *LoginRequest) (*LoginResult, error)
	Refresh(context.Context, *CredentialBlob) (*RefreshResult, error)
	GetProfile(context.Context, *CredentialBlob) (*AccountProfile, error)
	// 模型目录
	ListModels(context.Context, *CredentialBlob) (*ModelList, error)
	// 核心链路：统一信封进，事件流出
	Chat(*ChatRequest, grpc.ServerStreamingServer[StreamEvent]) error
	// 任务能力（核心调度触发时调用）
	ListTaskCapabilities(context.Context, *TaskCapabilitiesRequest) (*TaskCapabilities, error)
	RunTask(context.Context, *RunTaskRequest) (*RunTaskResponse, error)
	mustEmbedUnimplementedClawPluginServer()
}

// UnimplementedClawPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClawPluginServer struct{}

func (UnimplementedClawPluginServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedClawPluginServer) Login(context.Context, *LoginRequest) (*LoginResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedClawPluginServer) Refresh(context.Context, *CredentialBlob) (*RefreshResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedClawPluginServer) GetProfile(context.Context, *CredentialBlob) (*AccountProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedClawPluginServer) ListModels(context.Context, *CredentialBlob) (*ModelList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedClawPluginServer) Chat(*ChatRequest, grpc.ServerStreamingServer[StreamEvent]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedClawPluginServer) ListTaskCapabilities(context.Context, *TaskCapabilitiesRequest) (*TaskCapabilities, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTaskCapabilities not implemented")
}
func (UnimplementedClawPluginServer) RunTask(context.Context, *RunTaskRequest) (*RunTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunTask not implemented")
}
func (UnimplementedClawPluginServer) mustEmbedUnimplementedClawPluginServer() {}
func (UnimplementedClawPluginServer) testEmbeddedByValue()                    {}

// UnsafeClawPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClawPluginServer will
// result in compilation errors.
type UnsafeClawPluginServer interface {
	mustEmbedUnimplementedClawPluginServer()
}

func RegisterClawPluginServer(s grpc.ServiceRegistrar, srv ClawPluginServer) {
	// If the following call panics, it indicates UnimplementedClawPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClawPlugin_ServiceDesc, srv)
}

func _ClawPlugin_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawPluginServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClawPlugin_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawPluginServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClawPlugin_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawPluginServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClawPlugin_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawPluginServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClawPlugin_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialBlob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawPluginServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClawPlugin_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawPluginServer).Refresh(ctx, req.(*CredentialBlob))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClawPlugin_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialBlob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawPluginServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClawPlugin_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawPluginServer).GetProfile(ctx, req.(*CredentialBlob))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClawPlugin_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialBlob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawPluginServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClawPlugin_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawPluginServer).ListModels(ctx, req.(*CredentialBlob))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClawPlugin_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClawPluginServer).Chat(m, &grpc.GenericServerStream[ChatRequest, StreamEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClawPlugin_ChatServer = grpc.ServerStreamingServer[StreamEvent]

func _ClawPlugin_ListTaskCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawPluginServer).ListTaskCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClawPlugin_ListTaskCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawPluginServer).ListTaskCapabilities(ctx, req.(*TaskCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClawPlugin_RunTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawPluginServer).RunTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClawPlugin_RunTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawPluginServer).RunTask(ctx, req.(*RunTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClawPlugin_ServiceDesc is the grpc.ServiceDesc for ClawPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClawPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cph.v1.ClawPlugin",
	HandlerType: (*ClawPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _ClawPlugin_Handshake_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _ClawPlugin_Login_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _ClawPlugin_Refresh_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _ClawPlugin_GetProfile_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _ClawPlugin_ListModels_Handler,
		},
		{
			MethodName: "ListTaskCapabilities",
			Handler:    _ClawPlugin_ListTaskCapabilities_Handler,
		},
		{
			MethodName: "RunTask",
			Handler:    _ClawPlugin_RunTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _ClawPlugin_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sdk/proto/cph.proto",
}

const (
	ClawHost_Log_FullMethodName         = "/cph.v1.ClawHost/Log"
	ClawHost_StoreGet_FullMethodName    = "/cph.v1.ClawHost/StoreGet"
	ClawHost_StorePut_FullMethodName    = "/cph.v1.ClawHost/StorePut"
	ClawHost_GetProxy_FullMethodName    = "/cph.v1.ClawHost/GetProxy"
	ClawHost_GetSettings_FullMethodName = "/cph.v1.ClawHost/GetSettings"
)

// ClawHostClient is the client API for ClawHost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClawHost —— 插件作为 gRPC 客户端反向调用核心（回调注入）
type ClawHostClient interface {
	// 统一日志管道
	Log(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*Empty, error)
	// 状态读写（凭据之外的小状态，凭据经 RPC 返回值流转）
	StoreGet(ctx context.Context, in *StoreGetRequest, opts ...grpc.CallOption) (*StoreGetResponse, error)
	StorePut(ctx context.Context, in *StorePutRequest, opts ...grpc.CallOption) (*Empty, error)
	// 按分组取代理
	GetProxy(ctx context.Context, in *GetProxyRequest, opts ...grpc.CallOption) (*ProxyConfig, error)
	// 读插件设置（核心管理界面保存后即时生效）
	GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*GetSettingsResponse, error)
}

type clawHostClient struct {
	cc grpc.ClientConnInterface
}

func NewClawHostClient(cc grpc.ClientConnInterface) ClawHostClient {
	return &clawHostClient{cc}
}

func (c *clawHostClient) Log(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClawHost_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawHostClient) StoreGet(ctx context.Context, in *StoreGetRequest, opts ...grpc.CallOption) (*StoreGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreGetResponse)
	err := c.cc.Invoke(ctx, ClawHost_StoreGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawHostClient) StorePut(ctx context.Context, in *StorePutRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClawHost_StorePut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawHostClient) GetProxy(ctx context.Context, in *GetProxyRequest, opts ...grpc.CallOption) (*ProxyConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProxyConfig)
	err := c.cc.Invoke(ctx, ClawHost_GetProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawHostClient) GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*GetSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSettingsResponse)
	err := c.cc.Invoke(ctx, ClawHost_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClawHostServer is the server API for ClawHost service.
// All implementations must embed UnimplementedClawHostServer
// for forward compatibility.
//
// ClawHost —— 插件作为 gRPC 客户端反向调用核心（回调注入）
type ClawHostServer interface {
	// 统一日志管道
	Log(context.Context, *LogEntry) (*Empty, error)
	// 状态读写（凭据之外的小状态，凭据经 RPC 返回值流转）
	StoreGet(context.Context, *StoreGetRequest) (*StoreGetResponse, error)
	StorePut(context.Context, *StorePutRequest) (*Empty, error)
	// 按分组取代理
	GetProxy(context.Context, *GetProxyRequest) (*ProxyConfig, error)
	// 读插件设置（核心管理界面保存后即时生效）
	GetSettings(context.Context, *GetSettingsRequest) (*GetSettingsResponse, error)
	mustEmbedUnimplementedClawHostServer()
}

// UnimplementedClawHostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClawHostServer struct{}

func (UnimplementedClawHostServer) Log(context.Context, *LogEntry) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedClawHostServer) StoreGet(context.Context, *StoreGetRequest) (*StoreGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreGet not implemented")
}
func (UnimplementedClawHostServer) StorePut(context.Context, *StorePutRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StorePut not implemented")
}
func (UnimplementedClawHostServer) GetProxy(context.Context, *GetProxyRequest) (*ProxyConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProxy not implemented")
}
func (UnimplementedClawHostServer) GetSettings(context.Context, *GetSettingsRequest) (*GetSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedClawHostServer) mustEmbedUnimplementedClawHostServer() {}
func (UnimplementedClawHostServer) testEmbeddedByValue()                  {}

// UnsafeClawHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClawHostServer will
// result in compilation errors.
type UnsafeClawHostServer interface {
	mustEmbedUnimplementedClawHostServer()
}

func RegisterClawHostServer(s grpc.ServiceRegistrar, srv ClawHostServer) {
	// If the following call panics, it indicates UnimplementedClawHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClawHost_ServiceDesc, srv)
}

func _ClawHost_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawHostServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClawHost_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawHostServer).Log(ctx, req.(*LogEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClawHost_StoreGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawHostServer).StoreGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClawHost_StoreGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawHostServer).StoreGet(ctx, req.(*StoreGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClawHost_StorePut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorePutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawHostServer).StorePut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClawHost_StorePut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawHostServer).StorePut(ctx, req.(*StorePutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClawHost_GetProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawHostServer).GetProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClawHost_GetProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawHostServer).GetProxy(ctx, req.(*GetProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClawHost_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawHostServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClawHost_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawHostServer).GetSettings(ctx, req.(*GetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClawHost_ServiceDesc is the grpc.ServiceDesc for ClawHost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClawHost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cph.v1.ClawHost",
	HandlerType: (*ClawHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _ClawHost_Log_Handler,
		},
		{
			MethodName: "StoreGet",
			Handler:    _ClawHost_StoreGet_Handler,
		},
		{
			MethodName: "StorePut",
			Handler:    _ClawHost_StorePut_Handler,
		},
		{
			MethodName: "GetProxy",
			Handler:    _ClawHost_GetProxy_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _ClawHost_GetSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdk/proto/cph.proto",
}
